# Generated by Django 2.2.7 on 2019-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20191201_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
