# Generated by Django 2.2.7 on 2019-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20191201_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
